version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    restart: always
    volumes:
      - /books/lib/postgres/data
    ports:
      - "5433:5432"

  rabbit:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - /books/lib/rabbit/data

  web:
    build: .
    container_name: books
    restart: always
    depends_on:
      - db
      - rabbit
    command: bash entrypoint.sh
    volumes:
      - .:/proj/
      - static:/proj/static
    env_file:
      - .env

  celery:
    build: .
    container_name: celery
    command: celery -A Books worker -l INFO
    volumes:
      - /books/lib/celery/data
    depends_on:
      - rabbit
      - web
    env_file:
      - .env

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - static:/proj/static
    ports:
      - "81:80"
      - "443:443"
volumes:
  static: